// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldzWxpc39kZp-IA50eZRRf_dLCIMsBgA',
    appId: '1:823696470027:web:f33bc921fa3a2b9e17170e',
    messagingSenderId: '823696470027',
    projectId: 'prakfirebase-61303',
    authDomain: 'prakfirebase-61303.firebaseapp.com',
    storageBucket: 'prakfirebase-61303.appspot.com',
    measurementId: 'G-BF4XQM06E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEn3kfQ_SHWi1JVSocXu1k3yeBp1gFppI',
    appId: '1:823696470027:android:4aa8142ada6b520817170e',
    messagingSenderId: '823696470027',
    projectId: 'prakfirebase-61303',
    storageBucket: 'prakfirebase-61303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArBZFQXpuHJ3sDngD6sfFuHpme0a_CpW0',
    appId: '1:823696470027:ios:ad1f0a15399785cf17170e',
    messagingSenderId: '823696470027',
    projectId: 'prakfirebase-61303',
    storageBucket: 'prakfirebase-61303.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArBZFQXpuHJ3sDngD6sfFuHpme0a_CpW0',
    appId: '1:823696470027:ios:ad1f0a15399785cf17170e',
    messagingSenderId: '823696470027',
    projectId: 'prakfirebase-61303',
    storageBucket: 'prakfirebase-61303.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDldzWxpc39kZp-IA50eZRRf_dLCIMsBgA',
    appId: '1:823696470027:web:5b607d800cf6b90417170e',
    messagingSenderId: '823696470027',
    projectId: 'prakfirebase-61303',
    authDomain: 'prakfirebase-61303.firebaseapp.com',
    storageBucket: 'prakfirebase-61303.appspot.com',
    measurementId: 'G-7GWG1PNCW3',
  );

}