// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijQcPRR8XsnYW6BaG9fRoFgz67e4ecqw',
    appId: '1:221132289395:web:634401ce60962472654106',
    messagingSenderId: '221132289395',
    projectId: 'prakfirebase-16ee8',
    authDomain: 'prakfirebase-16ee8.firebaseapp.com',
    storageBucket: 'prakfirebase-16ee8.appspot.com',
    measurementId: 'G-RK5CS9P7K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_fR1B8l4lDoZew9h_QSutcGgIyZGURs',
    appId: '1:221132289395:android:8e92b150a7b802ea654106',
    messagingSenderId: '221132289395',
    projectId: 'prakfirebase-16ee8',
    storageBucket: 'prakfirebase-16ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmmLhld3m7GpWOrZIUrFnGj7wFfKJjd9w',
    appId: '1:221132289395:ios:529bf33295ac010c654106',
    messagingSenderId: '221132289395',
    projectId: 'prakfirebase-16ee8',
    storageBucket: 'prakfirebase-16ee8.appspot.com',
    iosBundleId: 'com.example.firebaseAuthGooglePertemuan10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmmLhld3m7GpWOrZIUrFnGj7wFfKJjd9w',
    appId: '1:221132289395:ios:529bf33295ac010c654106',
    messagingSenderId: '221132289395',
    projectId: 'prakfirebase-16ee8',
    storageBucket: 'prakfirebase-16ee8.appspot.com',
    iosBundleId: 'com.example.firebaseAuthGooglePertemuan10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCijQcPRR8XsnYW6BaG9fRoFgz67e4ecqw',
    appId: '1:221132289395:web:a88ad6058512802d654106',
    messagingSenderId: '221132289395',
    projectId: 'prakfirebase-16ee8',
    authDomain: 'prakfirebase-16ee8.firebaseapp.com',
    storageBucket: 'prakfirebase-16ee8.appspot.com',
    measurementId: 'G-9YC3M3VMJK',
  );
}
