// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgm5CCJBVMJPTNBRCwLbM1xCap03I8dRo',
    appId: '1:715424212411:web:cb90a9c170d56cd551509e',
    messagingSenderId: '715424212411',
    projectId: 'prakfirebase-1c1c3',
    authDomain: 'prakfirebase-1c1c3.firebaseapp.com',
    storageBucket: 'prakfirebase-1c1c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLVPIyNlUkokdLik6YMDrt-Ep5MglB6Q',
    appId: '1:715424212411:android:6a5699bf8a027d2351509e',
    messagingSenderId: '715424212411',
    projectId: 'prakfirebase-1c1c3',
    storageBucket: 'prakfirebase-1c1c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxz3KEbA0waI3QWhxw910r_tU5Q6CWug',
    appId: '1:715424212411:ios:75cb115f750e927d51509e',
    messagingSenderId: '715424212411',
    projectId: 'prakfirebase-1c1c3',
    storageBucket: 'prakfirebase-1c1c3.appspot.com',
    iosBundleId: 'com.example.firebaseAuthGooglePertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxz3KEbA0waI3QWhxw910r_tU5Q6CWug',
    appId: '1:715424212411:ios:75cb115f750e927d51509e',
    messagingSenderId: '715424212411',
    projectId: 'prakfirebase-1c1c3',
    storageBucket: 'prakfirebase-1c1c3.appspot.com',
    iosBundleId: 'com.example.firebaseAuthGooglePertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgm5CCJBVMJPTNBRCwLbM1xCap03I8dRo',
    appId: '1:715424212411:web:8cd8f4ae9952211751509e',
    messagingSenderId: '715424212411',
    projectId: 'prakfirebase-1c1c3',
    authDomain: 'prakfirebase-1c1c3.firebaseapp.com',
    storageBucket: 'prakfirebase-1c1c3.appspot.com',
  );
}
